<?php

namespace Database\Seeders;

use App\Models\Contact;
use Illuminate\Database\Seeder;

class ContactSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Creates 15 realistic sample contacts for user_id = 1.
     */
    public function run(): void
    {
        $contacts = [
            [
                'user_id'          => 1,
                'first_name'       => 'John',
                'last_name'        => 'Doe',
                'email'            => 'john.doe@google.com',
                'phone'            => '+1-650-555-0101',
                'company'          => 'Google',
                'job_title'        => 'Senior Software Engineer',
                'linkedin_url'     => 'https://linkedin.com/in/johndoe',
                'website'          => 'https://google.com',
                'country'          => 'United States',
                'city'             => 'Mountain View',
                'notes'            => 'Met at Google I/O. Interested in ML infrastructure roles.',
                'status'           => 'active',
                'source'           => 'conference',
                'last_contacted_at' => now()->subDays(10),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Sarah',
                'last_name'        => 'Chen',
                'email'            => 'sarah.chen@microsoft.com',
                'phone'            => '+1-425-555-0202',
                'company'          => 'Microsoft',
                'job_title'        => 'HR Manager',
                'linkedin_url'     => 'https://linkedin.com/in/sarahchen',
                'website'          => 'https://microsoft.com',
                'country'          => 'United States',
                'city'             => 'Redmond',
                'notes'            => 'Handles technical recruiting for Azure team.',
                'status'           => 'active',
                'source'           => 'linkedin',
                'last_contacted_at' => now()->subDays(5),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Prof. David',
                'last_name'        => 'Kim',
                'email'            => 'dkim@mit.edu',
                'phone'            => '+1-617-555-0303',
                'company'          => 'MIT',
                'job_title'        => 'Professor of Computer Science',
                'linkedin_url'     => 'https://linkedin.com/in/davidkim-mit',
                'website'          => 'https://people.csail.mit.edu/dkim',
                'country'          => 'United States',
                'city'             => 'Cambridge',
                'notes'            => 'Leading researcher in NLP. Potential PhD supervisor.',
                'status'           => 'active',
                'source'           => 'research_paper',
                'last_contacted_at' => now()->subDays(20),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Emily',
                'last_name'        => 'Rodriguez',
                'email'            => 'e.rodriguez@stanford.edu',
                'phone'            => null,
                'company'          => 'Stanford University',
                'job_title'        => 'Research Director',
                'linkedin_url'     => 'https://linkedin.com/in/emilyrodriguez',
                'website'          => 'https://cs.stanford.edu/~erodriguez',
                'country'          => 'United States',
                'city'             => 'Stanford',
                'notes'            => 'Works on AI safety. Spoke at NeurIPS 2024.',
                'status'           => 'active',
                'source'           => 'conference',
                'last_contacted_at' => now()->subDays(15),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Marcus',
                'last_name'        => 'Johnson',
                'email'            => 'mjohnson@nsf.gov',
                'phone'            => '+1-703-555-0505',
                'company'          => 'National Science Foundation',
                'job_title'        => 'Program Director',
                'linkedin_url'     => null,
                'website'          => 'https://nsf.gov',
                'country'          => 'United States',
                'city'             => 'Alexandria',
                'notes'            => 'Manages GRFP and graduate research fellowships.',
                'status'           => 'active',
                'source'           => 'website',
                'last_contacted_at' => now()->subDays(30),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Amanda',
                'last_name'        => 'Foster',
                'email'            => 'afoster@gatesfoundation.org',
                'phone'            => '+1-206-555-0606',
                'company'          => 'Gates Foundation',
                'job_title'        => 'Program Officer',
                'linkedin_url'     => 'https://linkedin.com/in/amandafoster',
                'website'          => 'https://gatesfoundation.org',
                'country'          => 'United States',
                'city'             => 'Seattle',
                'notes'            => 'Focuses on global health and education initiatives.',
                'status'           => 'active',
                'source'           => 'referral',
                'last_contacted_at' => now()->subDays(8),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Raj',
                'last_name'        => 'Patel',
                'email'            => 'raj.patel@openai.com',
                'phone'            => '+1-415-555-0707',
                'company'          => 'OpenAI',
                'job_title'        => 'Research Scientist',
                'linkedin_url'     => 'https://linkedin.com/in/rajpatel-ai',
                'website'          => null,
                'country'          => 'United States',
                'city'             => 'San Francisco',
                'notes'            => 'Works on alignment and RLHF. Very responsive on LinkedIn.',
                'status'           => 'active',
                'source'           => 'linkedin',
                'last_contacted_at' => now()->subDays(3),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Linda',
                'last_name'        => 'Weston',
                'email'            => 'l.weston@caltech.edu',
                'phone'            => '+1-626-555-0808',
                'company'          => 'Caltech',
                'job_title'        => 'Professor of Physics',
                'linkedin_url'     => null,
                'website'          => 'https://www.caltech.edu/~lweston',
                'country'          => 'United States',
                'city'             => 'Pasadena',
                'notes'            => 'Quantum computing research. NSF grant holder.',
                'status'           => 'active',
                'source'           => 'research_paper',
                'last_contacted_at' => now()->subDays(45),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Thomas',
                'last_name'        => 'Nguyen',
                'email'            => 'thomas.nguyen@amazon.com',
                'phone'            => '+1-206-555-0909',
                'company'          => 'Amazon',
                'job_title'        => 'HR Manager',
                'linkedin_url'     => 'https://linkedin.com/in/thomasnguyen',
                'website'          => null,
                'country'          => 'United States',
                'city'             => 'Seattle',
                'notes'            => 'Recruits for AWS and Alexa teams.',
                'status'           => 'active',
                'source'           => 'linkedin',
                'last_contacted_at' => now()->subDays(12),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Priya',
                'last_name'        => 'Sharma',
                'email'            => 'priya.sharma@deepmind.com',
                'phone'            => null,
                'company'          => 'DeepMind',
                'job_title'        => 'Research Engineer',
                'linkedin_url'     => 'https://linkedin.com/in/priyasharma-dm',
                'website'          => null,
                'country'          => 'United Kingdom',
                'city'             => 'London',
                'notes'            => 'Working on AlphaFold successor projects.',
                'status'           => 'active',
                'source'           => 'conference',
                'last_contacted_at' => now()->subDays(25),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Kevin',
                'last_name'        => 'O\'Brien',
                'email'            => 'kobrien@mit.edu',
                'phone'            => '+1-617-555-1111',
                'company'          => 'MIT',
                'job_title'        => 'Admissions Director',
                'linkedin_url'     => 'https://linkedin.com/in/kevinobrien-mit',
                'website'          => 'https://www.mit.edu/admissions',
                'country'          => 'United States',
                'city'             => 'Cambridge',
                'notes'            => 'Handles graduate program admissions.',
                'status'           => 'active',
                'source'           => 'website',
                'last_contacted_at' => now()->subDays(18),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Sofia',
                'last_name'        => 'Martinez',
                'email'            => 's.martinez@nih.gov',
                'phone'            => '+1-301-555-1212',
                'company'          => 'NIH',
                'job_title'        => 'Program Director',
                'linkedin_url'     => null,
                'website'          => 'https://nih.gov',
                'country'          => 'United States',
                'city'             => 'Bethesda',
                'notes'            => 'Oversees biomedical research funding programs.',
                'status'           => 'active',
                'source'           => 'website',
                'last_contacted_at' => now()->subDays(40),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'James',
                'last_name'        => 'Thompson',
                'email'            => 'jthompson@anthropic.com',
                'phone'            => '+1-415-555-1313',
                'company'          => 'Anthropic',
                'job_title'        => 'Research Director',
                'linkedin_url'     => 'https://linkedin.com/in/jamesthompson-ai',
                'website'          => null,
                'country'          => 'United States',
                'city'             => 'San Francisco',
                'notes'            => 'Leads interpretability research team.',
                'status'           => 'active',
                'source'           => 'conference',
                'last_contacted_at' => now()->subDays(7),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Grace',
                'last_name'        => 'Liu',
                'email'            => 'grace.liu@meta.com',
                'phone'            => '+1-650-555-1414',
                'company'          => 'Meta',
                'job_title'        => 'HR Manager',
                'linkedin_url'     => 'https://linkedin.com/in/graceliu-meta',
                'website'          => null,
                'country'          => 'United States',
                'city'             => 'Menlo Park',
                'notes'            => 'Recruits for FAIR (Fundamental AI Research).',
                'status'           => 'active',
                'source'           => 'linkedin',
                'last_contacted_at' => now()->subDays(22),
            ],
            [
                'user_id'          => 1,
                'first_name'       => 'Daniel',
                'last_name'        => 'Brooks',
                'email'            => 'd.brooks@spammy-recruiter.io',
                'phone'            => null,
                'company'          => 'Unknown Staffing Agency',
                'job_title'        => 'Recruiter',
                'linkedin_url'     => null,
                'website'          => null,
                'country'          => null,
                'city'             => null,
                'notes'            => 'Sent unsolicited emails. Marked as suppressed.',
                'status'           => 'suppressed',
                'source'           => 'manual',
                'last_contacted_at' => null,
            ],
        ];

        foreach ($contacts as $contact) {
            Contact::create($contact);
        }
    }
}
